"""Environment file generation for the Aetheris app.

Writes a .env next to the docker-compose.yml so `docker compose up`
picks up credentials automatically. A random AETHERIS_SECRET is generated
when none exists; existing .env files are never overwritten.
"""

from __future__ import annotations

import secrets
from pathlib import Path

_ENV_TEMPLATE = """# Aetheris - generated by aetheris-windows-installer
AETHERIS_APP_URL={app_url}
AETHERIS_SECRET={secret}
POSTGRES_USER=aetheris
POSTGRES_PASSWORD={db_password}
POSTGRES_DB=aetheris
"""


def generate_secret(length: int = 48) -> str:
    return secrets.token_urlsafe(length)


def write_env_file(env_path: Path, app_url: str = "http://localhost:3000") -> Path:
    """Create .env if missing; returns the path. Never overwrites existing."""
    if env_path.exists():
        return env_path
    content = _ENV_TEMPLATE.format(
        app_url=app_url,
        secret=generate_secret(),
        db_password=generate_secret(24),
    )
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(content, encoding="utf-8")
    return env_path
