"""Environment file generation for the Aetheris app.

Writes a .env next to the docker-compose file so `docker compose up` picks
up credentials automatically. A random AETHERIS_SECRET is generated when
none exists; existing .env files are never overwritten.

Two database backends are supported:
  - postgres: the Docker stack provisions a PostgreSQL container and the
    .env carries the POSTGRES_* credentials.
  - sqlite: no database container is started; the app persists to a local
    .db file. The .env sets AETHERIS_DB_MODE=sqlite and a file: DATABASE_URL.

When env_timing is "later" the .env is intentionally not written and the
installer reports where to create it after the fact.
"""

from __future__ import annotations

import secrets
from pathlib import Path

_ENV_TEMPLATE = """# Aetheris - generated by aetheris-windows-installer
AETHERIS_APP_URL={app_url}
AETHERIS_SECRET={secret}
POSTGRES_USER=aetheris
POSTGRES_PASSWORD={db_password}
POSTGRES_DB=aetheris
"""

_ENV_SQLITE_TEMPLATE = """# Aetheris - generated by aetheris-windows-installer (sqlite test mode)
AETHERIS_APP_URL={app_url}
AETHERIS_SECRET={secret}
AETHERIS_DB_MODE=sqlite
DATABASE_URL=file:/data/aetheris.db
"""


def generate_secret(length: int = 48) -> str:
    return secrets.token_urlsafe(length)


def write_env_file(
    env_path: Path,
    app_url: str = "http://localhost:3000",
    db_mode: str = "postgres",
    env_timing: str = "now",
) -> Path | None:
    """Create .env if missing and the timing is 'now'. Returns the path, or
    None when the file was deliberately skipped (env_timing='later')."""
    if env_timing == "later":
        return None
    if env_path.exists():
        return env_path

    if db_mode == "sqlite":
        content = _ENV_SQLITE_TEMPLATE.format(
            app_url=app_url,
            secret=generate_secret(),
        )
    else:
        content = _ENV_TEMPLATE.format(
            app_url=app_url,
            secret=generate_secret(),
            db_password=generate_secret(24),
        )
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(content, encoding="utf-8")
    return env_path
